spring:
  cloud:
    nacos:
      discovery:
        server-addr: 124.70.101.93:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

# hystrix设置隔离策略为信号量，超时时间为2秒
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 2000
